server:
  port: 3344

spring:
  application:
    name: cloud-com.pl1111w.springcloud.config-server #服务名称
  rabbitmq:
    host: yourIp
    port: 5672
    username: admin
    password: 123456
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pl1111w/com.pl1111w.springcloud.config.git
          search-paths: prod,uat,sit  #扫描文件夹  uat sit配置相同名字的配置文件，后面文件夹的配置文件会覆盖前面的
      label: mater   #读取分支
    stream:
      binders:
        defaultRabbit:
          type: rabbit
      bindings:
        output:
          destination: studyExchange
          content-type: application/json
          binder: defaultRabbit
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
       defaultZone: http://localhost:7001/eureka
# 暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"