server:
  port: 7002
eureka:
  instance:
    hostname: eureka7002.com #eureka实例名称

  client:
    register-with-eureka: false #不向注册中心注册自己
    fetch-registry: false        #false表示自己就是注册中心，我的职责就是维护服务实例,并不区检索服务
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
       defaultZone: http://localhost:7001/eureka/

