server:
  port: 2002

spring:
  application:
    name: seata-storage-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_storage?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: Weixb4818
feign:
  hystrix:
    enabled: false
logging:
  level:
    io:
      seata: info

mybatis:
  mapper-locations: classpath*:mapper/*.xml
seata:
  tx-service-group: my_test_tx_group   #这里要特别注意和nacos中配置的要保持一直
  config:
    type: nacos
    nacos:
      #namespace:  #2.2中配置所在命名空间ID，入未配置 默认public空间
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      userName: nacos
      password: nacos
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      #namespace:    #2.2中配置所在命名空间ID，入未配置 默认public空间
      userName: nacos
      password: nacos
  service:
    vgroup-mapping:
      my_test_tx_group: default    #这里要特别注意和nacos中配置的要保持一直